package com.vv;

import module java.sql;

public class Java23ModuleTryOut {

    static final String DB_URL = "jdbc:postgresql://localhost:54320/postgres";
    static final String USER = "postgres";
    static final String PASS = "my_password";
    static final String QUERY = "SELECT id, first, last, age FROM Employees";

    public static void main(String[] args) {
		try {
			Class.forName("org.postgresql.Driver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
			return;
		}	
	    
        // Open a connection
        try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(QUERY);) {

            // Extract data from result set
            while (rs.next()) {
                // Retrieve by column name
                System.out.print("ID: " + rs.getInt("id"));
                System.out.print(", Age: " + rs.getInt("age"));
                System.out.print(", First: " + rs.getString("first"));
                System.out.println(", Last: " + rs.getString("last"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
	
	
	/**
   SQL	QUERIES
	-- DDL generated by DBeaver
	-- WARNING: It may differ from actual native database DDL
	CREATE TABLE information_schema.employees (
		id varchar(10485760) NULL,
		"first" varchar(10485760) NULL,
		"last" varchar(10485760) NULL,
		"ageEmployee" varchar(10485760) NULL
	);
	INSERT INTO public.employees
	(id, "first", "last", "ageEmployee")
	VALUES('1', 'vince', 'vauban', '41');
	**/
	
	/**
	DOCKER commands
	docker run -d --name my_postgres -v my_dbdata:/var/lib/postgresql/data -p 54320:5432 -e POSTGRES_PASSWORD=my_password postgres:13
    **/
	
	/**
	Java command
	java --enable-preview --source 23  -cp "C:\<PATH TO YOUR POSTGRES DRIVER>\postgresql-42.7.3.jar" Java23ModuleTryOut.java
	**/

}
